# Generated by Django 5.0.3 on 2024-03-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cognom1', models.CharField(max_length=100)),
                ('cognom2', models.CharField(max_length=100)),
                ('correu', models.EmailField(max_length=254)),
                ('curs', models.CharField(max_length=10)),
                ('moduls_matriculats', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('edat', models.PositiveIntegerField()),
                ('rol', models.CharField(max_length=100)),
                ('curs', models.TextField()),
            ],
        ),
    ]
